apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: {{ .Values.yarp.controllerClass | default .Release.Name }}
  labels:
    {{- include "netcorepal-ingress-controller.labels" . | nindent 4 }}
  annotations:
    ingressclass.kubernetes.io/is-default-class: "{{ .Values.yarp.isDefaultClass }}"
spec:
  controller: netcorepal.com/{{ .Values.yarp.controllerClass | default .Release.Name }}