name: Docker Image CI

on:
  push:
    branches: [ master,preview ]
    tags:
      - 1.*
  pull_request:
    branches: [ master,preview ]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v2.2.1
    - name: Docker Setup QEMU
      # You may pin to the exact commit or the version.
      # uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18
      uses: docker/setup-qemu-action@v2.1.0
      
    - uses: actions/checkout@v3
    - name: Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
      uses: docker/login-action@v2.1.0
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        registry: ${{ env.REGISTRY }}
        # Username used to log against the Docker registry
        username: ${{ github.actor }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4.1.1
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        # List of tags as key-value pair attributes
        tags: |
          latest
          type=ref,event=branch
          type=ref,event=tag
          type=schedule,pattern={{date 'YYYYMMDDHHmmss'}}
          type=ref,event=pr
    - name: Build and push Docker images
      # You may pin to the exact commit or the version.
      # uses: docker/build-push-action@e551b19e49efd4e98792db7592c17c09b89db8d8
      uses: docker/build-push-action@v3.2.0
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        file: src/NetCorePal.IngressController/Dockerfile
        platforms: linux/amd64
